version: "3.8"

services:
    dns:
        image: bind
        build: 
            context: .
            dockerfile: dockerfile
        restart: always
        ports:
            - "53:53/udp"
            - "53:53/tcp"
            - "953:953/tcp"
